include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Every public member of a package this small should be documented.
    - public_member_api_docs
    - always_declare_return_types
    - avoid_dynamic_calls
    - directives_ordering
    - prefer_final_locals
    - prefer_relative_imports
    - sort_pub_dependencies
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - use_super_parameters
